/**
 * Seed script for SCP NDOKI & ASSOCIES
 * JurisLink v3.8.65
 * 
 * Run: npx tsx prisma/seed-scp-ndoki.ts
 */

import { PrismaClient } from '@prisma/client'
import { hash } from 'bcryptjs'

const DATABASE_URL = 'postgresql://postgres.zosqktvmihtkqbbgdbgx:xoTozRtY5jJqu2ma@aws-1-eu-west-3.pooler.supabase.com:5432/postgres'
const db = new PrismaClient({ datasourceUrl: DATABASE_URL })

const NOW = new Date()
const DAYS_AGO = (d: number) => new Date(NOW.getTime() - d * 86400000)
const DAYS_LATER = (d: number) => new Date(NOW.getTime() + d * 86400000)

// UUIDs will be generated by Prisma, we store references after creation
let TENANT_ID = ''
const USER_IDS: Record<string, string> = {}
const CLIENT_IDS: Record<string, string> = {}
const CASE_IDS: Record<string, string> = {}
const EVENT_IDS: Record<string, string> = {}

const USERS = [
  { fullName: 'Me Serge Ndoki', email: 's.ndoki@scp-ndoki.com', role: 'associate', phone: '+237 6 99 00 01 01', password: 'Ndoki2024!' },
  { fullName: 'Jean-Paul Mbarga', email: 'jp.mbarga@scp-ndoki.com', role: 'lawyer', phone: '+237 6 99 00 02 02', password: 'Mbarga2024!' },
  { fullName: 'Claire Nkoulou', email: 'c.nkoulou@scp-ndoki.com', role: 'lawyer', phone: '+237 6 99 00 03 03', password: 'Nkoulou2024!' },
  { fullName: 'Patrice Owona', email: 'p.owona@scp-ndoki.com', role: 'collaborator', phone: '+237 6 99 00 04 04', password: 'Owona2024!' },
  { fullName: 'Sophie Essomba', email: 's.essomba@scp-ndoki.com', role: 'secretary', phone: '+237 6 99 00 05 05', password: 'Essomba2024!' },
  { fullName: 'Aimée Fotso', email: 'a.fotso@scp-ndoki.com', role: 'accountant', phone: '+237 6 99 00 06 06', password: 'Fotso2024!' },
  { fullName: 'Marc Tagne', email: 'm.tagne@scp-ndoki.com', role: 'lawyer', phone: '+237 6 99 00 07 07', password: 'Tagne2024!' },
  { fullName: 'Alain Bikay', email: 'a.bikay@scp-ndoki.com', role: 'jurist', phone: '+237 6 99 00 08 08', password: 'Bikay2024!' },
  { fullName: 'Isabelle Nganou', email: 'i.nganou@scp-ndoki.com', role: 'assistant', phone: '+237 6 99 00 09 09', password: 'Nganou2024!' },
]

const CLIENTS = [
  { fullName: 'Société CAMARA SARL', company: 'CAMARA SARL', clientType: 'entreprise', email: 'contact@camara.cm', phone: '+237 6 77 11 22 33', city: 'Douala', country: 'Cameroun', niu: 'M1234567890A', source: 'parrainage', riskLevel: 'faible' },
  { fullName: 'Marie Dupont', company: null, clientType: 'particulier', email: 'marie.dupont@yahoo.fr', phone: '+237 6 55 44 33 22', city: 'Yaoundé', country: 'Cameroun', source: 'internet', riskLevel: 'faible' },
  { fullName: 'Pierre Bikay', company: 'Bikay & Fils', clientType: 'entreprise', email: 'p.bikay@bikay-fils.cm', phone: '+237 6 33 22 11 00', city: 'Douala', country: 'Cameroun', niu: 'M0987654321B', source: 'referral', riskLevel: 'moyen' },
  { fullName: 'Emmanuel Kengne', company: null, clientType: 'particulier', email: 'e.kengne@gmail.com', phone: '+237 6 99 88 77 66', city: 'Douala', country: 'Cameroun', source: 'internet', riskLevel: 'faible' },
  { fullName: 'Groupe MANFOUMBI SA', company: 'Groupe MANFOUMBI', clientType: 'entreprise', email: 'juridique@manfoumbi.cm', phone: '+237 6 22 33 44 55', city: 'Douala', country: 'Cameroun', niu: 'M1122334455C', source: 'parrainage', riskLevel: 'eleve' },
  { fullName: 'Georges Owona', company: null, clientType: 'particulier', email: 'g.owona@orange.cm', phone: '+237 6 44 55 66 77', city: 'Yaoundé', country: 'Cameroun', source: 'ancien_client', riskLevel: 'faible' },
  { fullName: 'Famille Nkoulou Mbarga', company: null, clientType: 'particulier', email: 'famille.nkoulou@gmail.com', phone: '+237 6 11 22 33 44', city: 'Douala', country: 'Cameroun', source: 'parrainage', riskLevel: 'faible' },
  { fullName: 'ABC Corporation Ltd', company: 'ABC Corp', clientType: 'entreprise', email: 'legal@abccorp.com', phone: '+237 6 66 77 88 99', city: 'Douala', country: 'Cameroun', niu: 'M5566778899D', source: 'internet', riskLevel: 'moyen' },
  { fullName: 'Paul Etoundi', company: null, clientType: 'particulier', email: 'p.etoundi@gmail.com', phone: '+237 6 88 99 00 11', city: 'Yaoundé', country: 'Cameroun', source: 'tribunal', riskLevel: 'eleve' },
  { fullName: 'Famille Mbarga Ndong', company: null, clientType: 'particulier', email: 'mbarga.ndong@yahoo.fr', phone: '+237 6 22 11 00 99', city: 'Edéa', country: 'Cameroun', source: 'parrainage', riskLevel: 'faible' },
  { fullName: 'Thérèse Ngassa', company: null, clientType: 'particulier', email: 't.ngassa@gmail.com', phone: '+237 6 33 44 55 66', city: 'Douala', country: 'Cameroun', source: 'internet', riskLevel: 'faible' },
  { fullName: 'Compagnie APA Assurance SA', company: 'APA Assurance', clientType: 'entreprise', email: 'sinistres@apa-assurance.cm', phone: '+237 6 55 66 77 88', city: 'Douala', country: 'Cameroun', niu: 'M9988776655E', source: 'parrainage', riskLevel: 'moyen' },
  { fullName: 'Jean Mandengue', company: null, clientType: 'particulier', email: 'j.mandengue@gmail.com', phone: '+237 6 77 88 99 00', city: 'Douala', country: 'Cameroun', source: 'ancien_client', riskLevel: 'faible' },
  { fullName: 'SARL PALMEX Cameroun', company: 'PALMEX', clientType: 'entreprise', email: 'direction@palmex.cm', phone: '+237 6 44 33 22 11', city: 'Douala', country: 'Cameroun', niu: 'M4433221100F', source: 'referral', riskLevel: 'eleve' },
  { fullName: 'SARL MANGA Frères', company: 'MANGA Frères', clientType: 'entreprise', email: 'liquidation@manga-freres.cm', phone: '+237 6 11 00 99 88', city: 'Yaoundé', country: 'Cameroun', niu: 'M6655443322G', source: 'tribunal', riskLevel: 'eleve' },
  { fullName: 'Roger Tchoumba', company: null, clientType: 'particulier', email: 'r.tchoumba@gmail.com', phone: '+237 6 99 88 77 00', city: 'Bafoussam', country: 'Cameroun', source: 'tribunal', riskLevel: 'eleve' },
  { fullName: 'Société JOKO Industries', company: 'JOKO Industries', clientType: 'entreprise', email: 'pi@joko-industries.cm', phone: '+237 6 22 33 44 00', city: 'Douala', country: 'Cameroun', niu: 'M7788990011H', source: 'internet', riskLevel: 'moyen' },
]

const CASES = [
  { title: 'Litige commercial CAMARA c/ Fournisseur XYZ', description: 'Contestation de livraison non conforme de marchandises. Le fournisseur XYZ a livré des produits ne respectant pas les spécifications du contrat signé le 15/01/2024. Demande en résolution et dommages-intérêts.', caseType: 'commercial', status: 'en_cours', priority: 'haute', adversary: 'Fournisseur XYZ SARL', jurisdiction: 'TPI Douala', amountInDispute: 15000000, billingType: 'horaire', clientKey: 'Société CAMARA SARL', assignees: ['Me Serge Ndoki', 'Jean-Paul Mbarga'], ref: 'NDK-2024-001' },
  { title: 'Divorce Dupont c/ Dupont', description: 'Demande de divorce pour faute. Monsieur Dupont a commis des actes de violence conjugale. Mme Dupont demande la garde exclusive des deux enfants mineurs, une pension alimentaire et la partition des biens mobiliers et immobiliers.', caseType: 'civil', status: 'en_cours', priority: 'normale', adversary: 'Maître Charles Dupont', jurisdiction: 'TGI Yaoundé', amountInDispute: 5000000, billingType: 'forfait', clientKey: 'Marie Dupont', assignees: ['Claire Nkoulou'], ref: 'NDK-2024-002' },
  { title: 'Contentieux foncier - Terrain Bikay & Fils', description: 'Litige portant sur la propriété d\'un terrain de 2000 m² à Bonapriso. Le vendeur initial conteste la validité de la vente. Expertise topographique réalisée le 10/03/2024.', caseType: 'civil', status: 'ouvert', priority: 'haute', adversary: 'Ancien propriétaire Alain Mbarga', jurisdiction: 'TPI Douala', amountInDispute: 45000000, billingType: 'forfait', clientKey: 'Pierre Bikay', assignees: ['Me Serge Ndoki', 'Alain Bikay'], ref: 'NDK-2024-003' },
  { title: 'Licenciement abusif - Kengne c/ Bâtipro SARL', description: 'M. Kengne a été licencié sans motif légitime après 8 ans de service. Demande de réintégration, paiement des salaires arriérés et dommages-intérêts pour préjudice moral et matériel.', caseType: 'social', status: 'en_cours', priority: 'urgente', adversary: 'SARL Bâtipro', jurisdiction: 'TGI Douala', amountInDispute: 12000000, billingType: 'horaire', clientKey: 'Emmanuel Kengne', assignees: ['Claire Nkoulou', 'Patrice Owona'], ref: 'NDK-2024-004' },
  { title: 'Recours fiscal - Groupe MANFOUMBI', description: 'Contestation de redressement fiscal de 85 millions FCFA opéré par la DGI pour les exercices 2021-2023. Le groupe conteste les majorations et pénalités appliquées.', caseType: 'administratif', status: 'ouvert', priority: 'urgente', adversary: 'Direction Générale des Impôts', jurisdiction: 'Tribunal Administratif du Centre', amountInDispute: 85000000, billingType: 'horaire', clientKey: 'Groupe MANFOUMBI SA', assignees: ['Me Serge Ndoki', 'Jean-Paul Mbarga', 'Alain Bikay'], ref: 'NDK-2024-005' },
  { title: 'Responsabilité civile - Accident Owona', description: 'M. Owona a été victime d\'un accident de la circulation causé par un chauffeur du transport en commun. Fracture fémur gauche, hospitalisation 3 semaines, ITT de 45 jours.', caseType: 'civil', status: 'en_cours', priority: 'haute', adversary: 'Société de transport RAPIDO Express', jurisdiction: 'TPI Douala', amountInDispute: 20000000, billingType: 'success_fee', clientKey: 'Georges Owona', assignees: ['Jean-Paul Mbarga', 'Marc Tagne'], ref: 'NDK-2024-006' },
  { title: 'Succession Nkoulou Mbarga', description: 'Réglement de la succession de feu Joseph Nkoulou Mbarga décédé le 20/01/2024. 4 héritiers à inventorier les biens, évaluer l\'actif et le passif, et procéder au partage. Biens immobiliers à Douala et Yaoundé.', caseType: 'civil', status: 'ouvert', priority: 'normale', adversary: null, jurisdiction: 'Notaire associé', amountInDispute: 120000000, billingType: 'forfait', clientKey: 'Famille Nkoulou Mbarga', assignees: ['Claire Nkoulou', 'Patrice Owona'], ref: 'NDK-2024-007' },
  { title: 'Arbitrage commercial ABC Corp c/ XYZ Ltd', description: 'Arbitrage CCI portant sur l\'inexécution d\'un contrat de distribution exclusive en Afrique Centrale. Clause compromissoire du contrat du 05/06/2023.', caseType: 'commercial', status: 'en_cours', priority: 'haute', adversary: 'XYZ Ltd (Nigeria)', jurisdiction: 'Cour Commune de Justice et d\'Arbitrage (CCJA)', amountInDispute: 200000000, billingType: 'horaire', clientKey: 'ABC Corporation Ltd', assignees: ['Me Serge Ndoki', 'Jean-Paul Mbarga'], ref: 'NDK-2024-008' },
  { title: 'Affaire pénale - Paul Etoundi', description: 'Défense de M. Etoundi poursuivi pour abus de confiance et détournement de fonds dans le cadre de sa gestion d\'une coopérative agricole. Prévention: détournement de 35 millions FCFA.', caseType: 'penal', status: 'en_cours', priority: 'urgente', adversary: 'Ministère Public', jurisdiction: 'TPI Yaoundé', amountInDispute: 35000000, billingType: 'forfait', clientKey: 'Paul Etoundi', assignees: ['Me Serge Ndoki', 'Marc Tagne'], ref: 'NDK-2024-009' },
  { title: 'Expropriation - Famille Mbarga Ndong', description: 'Contestation de l\'expropriation d\'un terrain familial de 5000 m² à Edéa pour cause d\'utilité publique. Indemnisation proposée jugée insuffisante par rapport à la valeur marchande.', caseType: 'administratif', status: 'ouvert', priority: 'haute', adversary: 'État du Cameroun / MINPAT', jurisdiction: 'Tribunal Administratif du Littoral', amountInDispute: 60000000, billingType: 'horaire', clientKey: 'Famille Mbarga Ndong', assignees: ['Jean-Paul Mbarga', 'Alain Bikay'], ref: 'NDK-2024-010' },
  { title: 'Harcèlement au travail - Ngassa c/ LOGICAM', description: 'Mme Ngassa dénonce un harcèlement moral et sexuel de la part de son supérieur hiérarchique chez LOGICAM. Demande de résiliation aux torts de l\'employeur et dommages-intérêts.', caseType: 'social', status: 'nouveau', priority: 'haute', adversary: 'Société LOGICAM SA', jurisdiction: 'TGI Douala', amountInDispute: 15000000, billingType: 'horaire', clientKey: 'Thérèse Ngassa', assignees: ['Claire Nkoulou'], ref: 'NDK-2024-011' },
  { title: 'Litige assurance - APA c/ Mandengue', description: 'La Compagnie APA refuse d\'indemniser M. Mandengue pour un sinistre incendie survenu le 12/02/2024. Contestation de la clause d\'exclusion invoquée par l\'assureur.', caseType: 'civil', status: 'en_cours', priority: 'normale', adversary: 'APA Assurance SA', jurisdiction: 'TPI Douala', amountInDispute: 25000000, billingType: 'forfait', clientKey: 'Jean Mandengue', assignees: ['Patrice Owona'], ref: 'NDK-2024-012' },
  { title: 'Contrefaçon marque JOKO Industries', description: 'Action en contrefaçon et concurrence déloyale contre une société chinoise qui commercialise des produits sous une marque similaire « JOKOO » sur le marché camerounais et centrafricain.', caseType: 'commercial', status: 'ouvert', priority: 'haute', adversary: 'Société chinoise JOKOO Ltd', jurisdiction: 'TGI Douala / OAPI', amountInDispute: 50000000, billingType: 'horaire', clientKey: 'Société JOKO Industries', assignees: ['Me Serge Ndoki', 'Alain Bikay'], ref: 'NDK-2024-013' },
  { title: 'Garde d\'enfants - Affaire Fotso', description: 'Litige portant sur la garde des deux enfants mineurs du couple Fotso après séparation. Le père demande la garde alternée, la mère souhaite la garde exclusive.', caseType: 'civil', status: 'en_cours', priority: 'normale', adversary: 'Monsieur André Fotso', jurisdiction: 'TGI Yaoundé', amountInDispute: 0, billingType: 'forfait', clientKey: 'Compagnie APA Assurance SA', isSecret: true, assignees: ['Claire Nkoulou'], ref: 'NDK-2024-014' },
  { title: 'Contentieux bancaire - PALMEX c/ BCEAO', description: 'SARL PALMEX conteste un débit non autorisé de 120 millions FCFA opéré par la BCEAO sur son compte. Dysfonctionnement du système de paiement interbancaire identifié.', caseType: 'commercial', status: 'nouveau', priority: 'urgente', adversary: 'BEAC / Banque commerciale', jurisdiction: 'TPI Douala', amountInDispute: 120000000, billingType: 'success_fee', clientKey: 'SARL PALMEX Cameroun', assignees: ['Me Serge Ndoki', 'Jean-Paul Mbarga'], ref: 'NDK-2024-015' },
  { title: 'Vente immeuble Douala - Contentieux', description: 'Annulation d\'une vente d\'immeuble pour vice du consentement. L\'acquéreur découvre des vices cachés majeurs (fondations non conformes) après la signature.', caseType: 'civil', status: 'clos', priority: 'normale', adversary: 'Promoteur immobilier HOUSING CAM', jurisdiction: 'TPI Douala', amountInDispute: 35000000, billingType: 'forfait', clientKey: 'Georges Owona', assignees: ['Patrice Owona', 'Marc Tagne'], ref: 'NDK-2023-016' },
  { title: 'Procédure collective - SARL MANGA Frères', description: 'Mandat de redressement judiciaire de la SARL MANGA Frères. Dette totale estimée à 500 millions FCFA. Proposition de plan de continuation avec abandon de créances.', caseType: 'commercial', status: 'en_cours', priority: 'urgente', adversary: 'Ensemble des créanciers', jurisdiction: 'TGI Yaoundé', amountInDispute: 500000000, billingType: 'forfait', clientKey: 'SARL MANGA Frères', assignees: ['Me Serge Ndoki', 'Alain Bikay', 'Patrice Owona'], ref: 'NDK-2024-017' },
  { title: 'Vol aggravé - Affaire Tchoumba', description: 'Défense de M. Tchoumba poursuivi pour vol aggravé avec effraction dans une habitation. Prévention: vol de bijoux et espèces d\'une valeur de 10 millions FCFA.', caseType: 'penal', status: 'en_cours', priority: 'urgente', adversary: 'Ministère Public', jurisdiction: 'TPI Bafoussam', amountInDispute: 10000000, billingType: 'forfait', clientKey: 'Roger Tchoumba', assignees: ['Marc Tagne'], ref: 'NDK-2024-018' },
  { title: 'Permis de construire refusé - SCI Akwa', description: 'Recours contre le refus de permis de construire pour un immeuble R+5 à Akwa Nord. La mairie motive le refus par non-conformité au POS en vigueur.', caseType: 'administratif', status: 'nouveau', priority: 'normale', adversary: 'Mairie de Douala 5ème', jurisdiction: 'Tribunal Administratif du Littoral', amountInDispute: 80000000, billingType: 'horaire', clientKey: 'Société CAMARA SARL', assignees: ['Alain Bikay'], ref: 'NDK-2024-019' },
  { title: 'Fusion SCIE-MAN - Conseil juridique', description: 'Conseil et assistance juridique dans le cadre de la fusion-absorption de la SCIE par la MANFOUMBI SA. Rédaction des actes, vérification diligente et formalités OHADA.', caseType: 'commercial', status: 'en_cours', priority: 'haute', adversary: null, jurisdiction: 'RCCM Douala', amountInDispute: 0, billingType: 'forfait', clientKey: 'Groupe MANFOUMBI SA', assignees: ['Me Serge Ndoki', 'Jean-Paul Mbarga', 'Alain Bikay'], ref: 'NDK-2024-020' },
]

async function seed() {
  console.log('🌱 Seeding SCP NDOKI & ASSOCIES...')

  // 1. Create Tenant
  console.log('   Creating tenant...')
  const tenant = await db.tenant.upsert({
    where: { slug: 'scp-ndoki-associes' },
    update: {},
    create: {
      name: 'SCP NDOKI & ASSOCIES',
      slug: 'scp-ndoki-associes',
      email: 'contact@scp-ndoki.com',
      phone: '+237 6 99 00 00 00',
      address: '45 Rue Joss, Bonanjo',
      city: 'Douala',
      country: 'Cameroun',
      niu: 'M0012345678Z',
      plan: 'premium',
      maxUsers: 20,
      maxStorageGb: 50,
      isActive: true,
    },
  })
  TENANT_ID = tenant.id
  console.log(`   ✅ Tenant created: ${tenant.id}`)

  // 2. Create Currency XAF if not exists
  const xaf = await db.currency.upsert({
    where: { code: 'XAF' },
    update: {},
    create: { code: 'XAF', name: 'Franc CFA BEAC', symbol: 'FCFA' },
  })

  // 3. Create Subscription
  let plan = await db.subscriptionPlan.findFirst({ where: { slug: 'premium' } })
  if (!plan) {
    plan = await db.subscriptionPlan.create({
      data: {
        name: 'Premium', slug: 'premium',
        description: 'Plan premium pour cabinets de taille moyenne',
        priceAnnual: 480000, priceSemiAnnual: 260000, priceQuarterly: 140000, priceMonthly: 50000,
        maxUsers: 20, maxStorageGb: 50, hasAI: true, isActive: true, sortOrder: 3,
        features: JSON.stringify(['Gestion complète', 'Facturation', 'Calendrier', 'Rapports avancés', 'IA intégrée', 'Support prioritaire']),
      },
    })
  }
  await db.subscription.upsert({
    where: { tenantId: TENANT_ID },
    update: { planId: plan.id },
    create: {
      tenantId: TENANT_ID, planId: plan.id,
      status: 'active', billingPeriod: 'annual',
      currentPeriodStart: new Date('2024-01-01'),
      currentPeriodEnd: new Date('2024-12-31'),
    },
  })

  // 4. Create Users
  console.log('   Creating 9 users...')
  for (const u of USERS) {
    const hashedPassword = await hash(u.password, 12)
    const user = await db.user.upsert({
      where: { email: u.email },
      update: {},
      create: {
        fullName: u.fullName, email: u.email, role: u.role, phone: u.phone,
        password: hashedPassword, tenantId: TENANT_ID, isActive: true,
      },
    })
    USER_IDS[u.fullName] = user.id
    console.log(`   ✅ User: ${u.fullName} (${u.role})`)
  }

  // 5. Create Clients
  console.log('   Creating 17 clients...')
  for (const c of CLIENTS) {
    const client = await db.client.create({
      data: {
        ...c, tenantId: TENANT_ID,
        responsibleLawyerId: USER_IDS['Me Serge Ndoki'],
      },
    })
    CLIENT_IDS[c.fullName] = client.id
  }
  console.log(`   ✅ ${CLIENTS.length} clients created`)

  // 6. Create Cases + Assignments + Notes + Tasks + Events
  console.log('   Creating 20 cases with related data...')
  for (let i = 0; i < CASES.length; i++) {
    const c = CASES[i]
    const caze = await db.case.create({
      data: {
        title: c.title,
        description: c.description,
        caseType: c.caseType,
        status: c.status,
        priority: c.priority,
        isSecret: c.isSecret || false,
        reference: c.ref,
        adversary: c.adversary,
        jurisdiction: c.jurisdiction,
        amountInDispute: c.amountInDispute,
        billingType: c.billingType,
        tenantId: TENANT_ID,
        clientId: CLIENT_IDS[c.clientKey],
        createdAt: DAYS_AGO(90 - i * 4),
      },
    })
    CASE_IDS[c.ref] = caze.id

    // Assignments
    for (const assigneeName of c.assignees) {
      await db.caseAssignment.create({
        data: { userId: USER_IDS[assigneeName], caseId: caze.id, tenantId: TENANT_ID },
      })
    }

    // Notes (2-3 per case)
    const notes = generateNotes(i, c)
    for (const note of notes) {
      await db.caseNote.create({
        data: { content: note.content, caseId: caze.id, authorId: note.authorId, tenantId: TENANT_ID, createdAt: note.date },
      })
    }

    // Tasks (1-3 per case)
    const tasks = generateTasks(i, c, caze.id)
    for (const task of tasks) {
      const assignee = c.assignees[0]
      await db.task.create({
        data: {
          title: task.title, description: task.description, status: task.status,
          priority: task.priority, dueDate: task.dueDate,
          tenantId: TENANT_ID, caseId: caze.id, createdAt: task.created,
        },
      })
    }

    // Events (0-2 per case)
    if (c.status !== 'clos' && c.status !== 'nouveau') {
      const events = generateEvents(i, c, caze.id)
      for (const ev of events) {
        const event = await db.event.create({
          data: {
            title: ev.title, description: ev.description,
            startTime: ev.start, endTime: ev.end,
            eventType: ev.type, criticality: ev.criticality,
            tenantId: TENANT_ID, caseId: caze.id,
            createdAt: DAYS_AGO(30 - i),
          },
        })
        EVENT_IDS[`${c.ref}-${ev.type}`] = event.id
        for (const aName of c.assignees.slice(0, 2)) {
          await db.eventAssignment.create({ data: { userId: USER_IDS[aName], eventId: event.id } })
        }
      }
    }
  }
  console.log(`   ✅ 20 cases created with assignments, notes, tasks, events`)

  // 7. Create Invoices (1 per case for non-fee cases)
  console.log('   Creating invoices...')
  let invoiceCount = 0
  for (let i = 0; i < CASES.length; i++) {
    const c = CASES[i]
    if (c.amountInDispute === 0) continue
    const amount = c.billingType === 'forfait' ? 750000 : Math.min(c.amountInDispute * 0.05, 3000000)
    const status = c.status === 'clos' ? 'paye' : i < 5 ? 'paye' : i < 12 ? 'non_paye' : 'partiel'
    const paid = status === 'paye' ? amount : status === 'partiel' ? amount * 0.4 : 0

    const invoice = await db.invoice.create({
      data: {
        invoiceNumber: `FAC-NDK-${String(i + 1).padStart(4, '0')}`,
        type: 'facture', amount, paidAmount: paid, status,
        issuedAt: DAYS_AGO(60 - i * 3),
        dueDate: DAYS_AGO(30 - i * 3),
        billingType: c.billingType,
        tenantId: TENANT_ID, clientId: CLIENT_IDS[c.clientKey],
        caseId: CASE_IDS[c.ref], currencyId: xaf.id,
      },
    })
    await db.invoiceLineItem.create({
      data: {
        description: `Honoraires - ${c.title.substring(0, 50)}...`,
        quantity: 1, unitPrice: amount, total: amount, sortOrder: 1, invoiceId: invoice.id,
      },
    })
    if (paid > 0) {
      await db.payment.create({
        data: {
          amount: paid, method: status === 'paye' ? 'virement' : 'mobile_money',
          status: 'complet', paidAt: DAYS_AGO(20 - i * 2),
          tenantId: TENANT_ID, invoiceId: invoice.id, recordedBy: USER_IDS['Aimée Fotso'],
        },
      })
    }
    invoiceCount++
  }
  console.log(`   ✅ ${invoiceCount} invoices created`)

  // 8. Create Time Entries
  console.log('   Creating time entries...')
  let timeEntryCount = 0
  const lawyers = USERS.filter(u => ['associate', 'lawyer', 'collaborator', 'jurist'].includes(u.role))
  for (const caseRef of Object.keys(CASE_IDS)) {
    const caze = CASES.find(c => c.ref === caseRef)!
    if (caze.status === 'clos') continue
    // 2-5 time entries per open case
    const count = 2 + Math.floor(Math.random() * 4)
    for (let j = 0; j < count; j++) {
      const lawyer = lawyers[Math.floor(Math.random() * lawyers.length)]
      const hours = 1 + Math.random() * 4
      const startTime = DAYS_AGO(30 - j * 3)
      const endTime = new Date(startTime.getTime() + hours * 3600000)
      await db.timeEntry.create({
        data: {
          description: `Travail sur dossier ${caseRef} - ${caze.caseType}`,
          startTime, endTime, duration: Math.round(hours * 3600),
          isBillable: true, hourlyRate: 25000, totalAmount: Math.round(hours * 25000),
          tenantId: TENANT_ID, userId: USER_IDS[lawyer.fullName],
          caseId: CASE_IDS[caseRef], createdAt: startTime,
        },
      })
      timeEntryCount++
    }
  }
  console.log(`   ✅ ${timeEntryCount} time entries created`)

  // 9. Create Communications
  console.log('   Creating communications...')
  const comms = [
    { type: 'email', subject: 'Transmission pièces dossier NDK-2024-001', content: 'Veuillez trouver ci-joint l\'ensemble des pièces justificatives pour le litige commercial.', sentById: 'Sophie Essomba', clientId: 'Société CAMARA SARL', caseRef: 'NDK-2024-001', daysAgo: 2, status: 'sent' },
    { type: 'email', subject: 'Rappel audience - TPI Douala 15/09', content: 'Nous vous rappelons que l\'audience est fixée au 15 septembre 2024 à 9h00 au TPI de Douala, chambre commerciale.', sentById: 'Isabelle Nganou', clientId: 'Emmanuel Kengne', caseRef: 'NDK-2024-004', daysAgo: 1, status: 'sent' },
    { type: 'courrier', subject: 'Mise en demeure - SARL Bâtipro', content: 'Mise en demeure de réintégrer M. Kengne sous peine de saisine du tribunal.', sentById: 'Claire Nkoulou', clientId: 'Emmanuel Kengne', caseRef: 'NDK-2024-004', daysAgo: 15, status: 'sent' },
    { type: 'email', subject: 'Conclusion réclamation fiscale MANFOUMBI', content: 'Transmission des conclusions récapitulatives pour le recours fiscal exercice 2021-2023.', sentById: 'Me Serge Ndoki', clientId: 'Groupe MANFOUMBI SA', caseRef: 'NDK-2024-005', daysAgo: 5, status: 'sent' },
    { type: 'email', subject: 'Demande de devis expert-comptable', content: 'Demande de devis pour expertise comptable dans le cadre de la procédure collective MANGA Frères.', sentById: 'Aimée Fotso', clientId: 'SARL MANGA Frères', caseRef: 'NDK-2024-017', daysAgo: 3, status: 'pending' },
    { type: 'tel', subject: 'Appel client - État du dossier', content: 'Appel téléphonique avec M. Mandengue concernant l\'avancement de son dossier d\'assurance.', sentById: 'Isabelle Nganou', clientId: 'Jean Mandengue', caseRef: 'NDK-2024-012', daysAgo: 1, status: 'sent' },
    { type: 'email', subject: 'Convocation assemblée créanciers', content: 'Convocation à l\'assemblée générale des créanciers de la SARL MANGA Frères prévue le 25/09/2024.', sentById: 'Sophie Essomba', clientId: 'SARL MANGA Frères', caseRef: 'NDK-2024-017', daysAgo: 0, status: 'pending' },
    { type: 'email', subject: 'Transmission acte fusion SCIE-MAN', content: 'Veuillez trouver ci-joint le projet d\'acte de fusion pour revue et validation.', sentById: 'Patrice Owona', clientId: 'Groupe MANFOUMBI SA', caseRef: 'NDK-2024-020', daysAgo: 2, status: 'sent' },
  ]
  for (const comm of comms) {
    await db.communication.create({
      data: {
        type: comm.type, subject: comm.subject, content: comm.content,
        status: comm.status,
        sentAt: comm.status === 'sent' ? DAYS_AGO(comm.daysAgo) : null,
        tenantId: TENANT_ID, clientId: CLIENT_IDS[comm.clientId],
        caseId: CASE_IDS[comm.caseRef], sentById: USER_IDS[comm.sentById],
        createdAt: DAYS_AGO(comm.daysAgo),
      },
    })
  }
  console.log(`   ✅ ${comms.length} communications created`)

  // 10. Create Messages between users
  console.log('   Creating messages...')
  const msgs = [
    { from: 'Jean-Paul Mbarga', to: 'Me Serge Ndoki', content: 'Maître, j\'ai préparé les conclusions pour le dossier CAMARA. Pouvez-vous les relire ?', daysAgo: 2 },
    { from: 'Me Serge Ndoki', to: 'Jean-Paul Mbarga', content: 'Très bien Jean-Paul, je les relève cet après-midi. Pensez à invoquer l\'article 1608 du Code Civil.', daysAgo: 2 },
    { from: 'Claire Nkoulou', to: 'Sophie Essomba', content: 'Sophie, peux-tu planifier le rendez-vous avec Mme Dupont pour jeudi prochain ?', daysAgo: 1 },
    { from: 'Sophie Essomba', to: 'Claire Nkoulou', content: 'C\'est noté Maître. Je lui propose jeudi 10h ou vendredi 14h.', daysAgo: 1 },
    { from: 'Patrice Owona', to: 'Alain Bikay', content: 'Alain, as-tu vérifié la jurisprudence OHADA sur la fusion que je t\'ai envoyée ?', daysAgo: 3 },
    { from: 'Alain Bikay', to: 'Patrice Owona', content: 'Oui, j\'ai trouvé 3 arrêts pertinents de la CCJA. Je t\'envoie le résumé ce soir.', daysAgo: 3 },
    { from: 'Marc Tagne', to: 'Me Serge Ndoki', content: 'Maître, le client Tchoumba souhaite vous voir en prison. Demain possible ?', daysAgo: 0 },
    { from: 'Aimée Fotso', to: 'Me Serge Ndoki', content: 'Maître, la facture MANFOUMBI du mois de juillet est en attente de paiement (15M FCFA).', daysAgo: 1 },
  ]
  for (const m of msgs) {
    await db.message.create({
      data: {
        content: m.content, tenantId: TENANT_ID,
        senderId: USER_IDS[m.from], receiverId: USER_IDS[m.to],
        createdAt: DAYS_AGO(m.daysAgo),
      },
    })
  }
  console.log(`   ✅ ${msgs.length} messages created`)

  // 11. Create Notifications
  console.log('   Creating notifications...')
  const notifs = [
    { title: 'Audience demain', message: 'Audience NDK-2024-004 au TGI Douala à 9h00', userId: 'Claire Nkoulou', category: 'event', daysAgo: 1 },
    { title: 'Facture en retard', message: 'La facture FAC-NDK-0008 dépasse l\'échéance depuis 5 jours', userId: 'Aimée Fotso', category: 'invoice', daysAgo: 5 },
    { title: 'Nouveau dossier assigné', message: 'Vous avez été assigné au dossier NDK-2024-019', userId: 'Alain Bikay', category: 'dossier', daysAgo: 2 },
    { title: 'Tâche en retard', message: 'La tâche "Rédiger conclusions" pour le dossier NDK-2024-001 est en retard', userId: 'Jean-Paul Mbarga', category: 'task', daysAgo: 3 },
    { title: 'Message reçu', message: 'Nouveau message de Jean-Paul Mbarga', userId: 'Me Serge Ndoki', category: 'message', daysAgo: 2 },
  ]
  for (const n of notifs) {
    await db.notification.create({
      data: {
        title: n.title, message: n.message, category: n.category, read: n.daysAgo > 3,
        tenantId: TENANT_ID, userId: USER_IDS[n.userId],
        createdAt: DAYS_AGO(n.daysAgo),
      },
    })
  }
  console.log(`   ✅ ${notifs.length} notifications created`)

  console.log('\n✅ Seed SCP NDOKI & ASSOCIES terminé avec succès !')
  console.log(`   Tenant: ${tenant.name} (${TENANT_ID})`)
  console.log(`   Users: ${USERS.length}`)
  console.log(`   Clients: ${CLIENTS.length}`)
  console.log(`   Cases: ${CASES.length}`)
  console.log('\n   Comptes de connexion :')
  for (const u of USERS) {
    console.log(`   - ${u.email} / ${u.password} (${u.role})`)
  }
}

function generateNotes(caseIndex: number, caze: typeof CASES[0]) {
  const authorId = USER_IDS[caze.assignees[0]]
  return [
    { content: `Ouverture du dossier. Premier contact client pris. Renseignements préliminaires collectés. ${caze.description.substring(0, 80)}...`, authorId, date: DAYS_AGO(85 - caseIndex * 4) },
    { content: `Analyse juridique approfondie réalisée. Identification des axes de défense et des pièces à produire. Point fait avec le client.`, authorId, date: DAYS_AGO(70 - caseIndex * 4) },
    ...(caze.status !== 'nouveau' ? [{ content: `Dossier en cours d\'instruction. Prochaines étapes: rassembler les dernières pièces et préparer les conclusions.`, authorId, date: DAYS_AGO(40 - caseIndex * 3) }] : []),
  ]
}

function generateTasks(caseIndex: number, caze: typeof CASES[0], caseId: string) {
  const tasks = [
    { title: 'Rassembler les pièces du dossier', description: 'Collecter l\'ensemble des documents et preuves nécessaires', status: 'terminee' as const, priority: 'haute' as const, dueDate: DAYS_AGO(60 - caseIndex * 3), created: DAYS_AGO(85 - caseIndex * 4) },
    { title: 'Rédiger les conclusions', description: 'Préparer les conclusions écrites pour le tribunal', status: caze.status === 'clos' ? 'terminee' as const : 'en_cours' as const, priority: 'haute' as const, dueDate: DAYS_LATER(7 + caseIndex), created: DAYS_AGO(50 - caseIndex * 3) },
  ]
  if (caze.status !== 'clos' && caze.status !== 'nouveau') {
    tasks.push({ title: 'Préparer l\'audience', description: 'Préparation des arguments et répliques pour l\'audience', status: 'a_faire' as const, priority: caze.priority as 'normale' | 'haute' | 'urgente', dueDate: DAYS_LATER(15 + caseIndex * 2), created: DAYS_AGO(20 - caseIndex * 2) })
  }
  return tasks
}

function generateEvents(caseIndex: number, caze: typeof CASES[0], caseId: string) {
  if (caze.caseType === 'penal') {
    return [
      { title: `Audience ${caze.ref}`, description: `Audience pénale - ${caze.jurisdiction}`, start: DAYS_LATER(5 + caseIndex), end: DAYS_LATER(5 + caseIndex), type: 'audience' as const, criticality: 'urgente' as const },
      { title: `RDV client prison`, description: `Visite au client en détention`, start: DAYS_LATER(2 + caseIndex), end: DAYS_LATER(2 + caseIndex), type: 'rdv' as const, criticality: 'importante' as const },
    ]
  }
  if (caze.caseType === 'social') {
    return [
      { title: `Audience prud\'homale ${caze.ref}`, description: `Audience au ${caze.jurisdiction}`, start: DAYS_LATER(10 + caseIndex), end: DAYS_LATER(10 + caseIndex), type: 'audience' as const, criticality: 'normale' as const },
      { title: `Conciliation`, description: `Tentative de conciliation préalable`, start: DAYS_AGO(10 + caseIndex * 2), end: DAYS_AGO(10 + caseIndex * 2), type: 'echeance' as const, criticality: 'normale' as const },
    ]
  }
  if (caze.jurisdiction?.includes('Administratif')) {
    return [
      { title: `Audience TA ${caze.ref}`, description: `Audience au ${caze.jurisdiction}`, start: DAYS_LATER(20 + caseIndex), end: DAYS_LATER(20 + caseIndex), type: 'audience' as const, criticality: 'importante' as const },
    ]
  }
  return [
    { title: `Audience ${caze.ref}`, description: `Audience au ${caze.jurisdiction || 'Tribunal'}`, start: DAYS_LATER(8 + caseIndex), end: DAYS_LATER(8 + caseIndex), type: 'audience' as const, criticality: caze.priority === 'urgente' ? 'urgente' as const : 'normale' as const },
    { title: `Réunion de préparation`, description: `Point d\'avancement sur le dossier ${caze.ref}`, start: DAYS_LATER(3 + caseIndex), end: DAYS_LATER(3 + caseIndex), type: 'reunion' as const, criticality: 'normale' as const },
  ]
}

seed()
  .catch(console.error)
  .finally(() => db.$disconnect())
